# Generated by Django 2.1.2 on 2018-11-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20181104_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publickey',
            name='key',
        ),
    ]
