# Generated by Django 2.1.2 on 2018-11-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20181112_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey_text',
            new_name='survey_title',
        ),
    ]
