# Generated by Django 2.1.2 on 2018-11-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20181121_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['question', 'feedback_text'], 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AddField(
            model_name='survey',
            name='results_published',
            field=models.BooleanField(default=False),
        ),
    ]
