# Generated by Django 2.1.2 on 2018-11-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20181125_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey_title',
            new_name='title',
        ),
    ]
