# Generated by Django 2.1.2 on 2018-12-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20181125_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='author',
        ),
    ]
