# Generated by Django 2.1.2 on 2018-12-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='date due'),
        ),
    ]
